### ISSUE TITLE
Crash with Stockholm's Norse dynamic province name

### ISSUE THREAD

**Issue by ShekPS** [matanki-saito/EU4dll#237] opened 2022-09-24 17:38 UTC
Reproduce step:
1. Start as Denmark
2. own_core 1 (Stockholm)
3. event norse_events.8
4. choose the first option

The game will crash.
Confirmed in both Japanese mod and Chinese mod.
For Japanese mod, I use only "jpmod_ap0_mod.zip" and "jpmod_ap1_mod.zip", that means I didn't use translation of dynamic province names.

After some test in our group, we think it's related to 
1. The Norse dynamic province name of Stockholm "Svíthjódh"
2. The font file

The name looks like this in common/province_names/norse.txt
UTF-8:
![图片](https://user-images.githubusercontent.com/26006407/192111295-d47f2cf0-3109-4c93-8da0-b6388e7326fe.png)
Windows-1252:
![图片](https://user-images.githubusercontent.com/26006407/192111313-3ca86c13-548e-422d-8827-fea1d8c112f1.png)

It didn't crash with a font created by myself, but displayed like this
![图片](https://user-images.githubusercontent.com/26006407/192111268-40980d71-8b91-47a0-9571-baa4b61bacbe.png)
seems Windows-1252 is used, but UTF-8 should be the correct one.

Other ways to avoid this crash:
Disable dynamic province names
or
Manually change a name for Stockholm (so the game will use your name instead of the dynamic name)

**Comment by matanki-saito** [comment] 2022-09-24 17:56
let me check

**Comment by matanki-saito** [comment] 2022-09-25 01:56
As you said, the problem seems to be caused by Encoding.
`common/province_names/norse.txt` has saved with utf-8, but it must be windows-1252.

The problem may be solved in 1.34.4, but we will try to solve it in DLL or Font.

**Comment by matanki-saito** [comment] 2022-09-25 08:57
Fix pg, check release59 please

**Comment by ShekPS** [comment] 2022-09-25 13:10
Unfortunately the Chinese mod still crashes. (I see it didn't crash in Japanese mod anymore)

Maybe we need to ask @bruceCzK to modify the Chinese font...

**Comment by matanki-saito** [comment] 2022-09-25 15:14
let me check. Try using the Mod below.
https://steamcommunity.com/sharedfiles/filedetails/?id=1999050560

**Comment by matanki-saito** [comment] 2022-09-26 23:06
Probably fixed in version 60.

**Comment by ShekPS** [comment] 2022-10-01 05:23
> Probably fixed in version 60.

Not crash with this version on my computer, with the Chinese Localisation mod.

**Closed as completed** 2022-10-01 07:16 UTC
Labels: Bug(major)
